app-template:
  defaultPodOptions:
    priorityClassName: system-node-critical

  controllers:
    generic-device-plugin:
      type: daemonset
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: ghcr.io/squat/generic-device-plugin
            tag: latest@sha256:dc192e164c69b03f156765793a1be62ca437709ae477b27ca7d8f3dcf5021576
          args:
            - --log-level=info
            - --domain=generic-device-plugin
            - --device
            - |
              name: zwave
              groups:
                - usb:
                    - vendor: "10c4"
                      device: "8a2a"
                - paths:
                    - path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130101F-if00-port0
                      mountPath: /dev/ttyACM0
            - --device
            - |
              name: zigbee
              groups:
                - usb:
                    - vendor: "10c4"
                      device: "ea60"
                - paths:
                    - path: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_72de2ed2c445ed11a8848da40a86e0b4-if00-port0
                      mountPath: /dev/ttyUSB0
            - --device
            - |
              name: coral
              groups:
                - count: 1
                  usb:
                    - vendor: "1a6e"
                      product: "089a"
                    - vendor: "18d1"
                      product: "9302"

          ports:
            - containerPort: 8080
              name: http

          resources:
            requests:
              cpu: 10m
            limits:
              memory: 64Mi

  persistence:
    dev:
      type: hostPath
      hostPath: /dev
    sys:
      type: hostPath
      hostPath: /sys
      globalMounts:
        - readOnly: true
    var-lib-kubelet-device-plugins:
      type: hostPath
      hostPath: /var/lib/kubelet/device-plugins
