app-template:
  controllers:
    zwave:
      initContainers:
        init-chmod-fix:
          image:
            repository: busybox
            tag: latest
          command: [ 'sh', '-c', 'chown -R 1001:1001 /usr/src/app/store && chmod -R u+rwX,g+rwX /usr/src/app/store' ]
          securityContext:
            runAsUser: 0 # Temporary root privileges to override stale root-owned files
            runAsNonRoot: false

      containers:
        app:
          image:
            repository: ghcr.io/zwave-js/zwave-js-ui
            tag: 11.24.3@sha256:3fef66d575ea0ea9d50aad3e05c36619228557cfa888557eac2035215a29a321
          env:
            TZ: America/Chicago
            PORT: &port 8091
          probes:
            liveness: &probes
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /health
                  port: *port
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 1
                failureThreshold: 3
            readiness: *probes
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
              generic-device-plugin/zwave: 1
            limits:
              memory: 512Mi
              generic-device-plugin/zwave: 1

  defaultPodOptions:
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      supplementalGroups: [20] # dialout group, required for /dev/ttyACM0 access
    tolerations:
      - key: "arm64"
        operator: "Exists"
  service:
    app:
      controller: zwave
      ports:
        http:
          port: *port
        websocket:
          port: 3000


  route:
    main:
      enabled: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Home
        gethomepage.dev/icon: zwavejs2mqtt
        gethomepage.dev/name: Zwavejs2mqtt
      parentRefs:
        - name: internal
          namespace: kube-system
          sectionName: https
      hostnames:
        - zwavejs2mqtt.rsr.net
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: zwavejs2mqtt
              port: 8091

  persistence:
    config:
      existingClaim: zwavejs2mqtt-config
      advancedMounts:
        zwave:
          app:
            - path: /usr/src/app/store
          init-chmod-fix:
            - path: /usr/src/app/store
    tmp:
      type: emptyDir
