
connect:
  connect:
    credentialsName: op-credentials
    credentialsKey: 1password-credentials.json
    api:
      imageRepository: ghcr.io/1password/connect-api
      serviceMonitor:
        enabled: true
    sync:
      imageRepository: ghcr.io/1password/connect-sync

