apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-git-ca-cert
  namespace: argocd
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    name: argocd-tls-certs-cm1
    creationPolicy: Owner
    template:
      engineVersion: v2
      kind: ConfigMap
      data:
        git.rsr.net: |
          {{ printf "{{ .ca_crt }}" }}

  data:
    - secretKey: ca_crt
      remoteRef:
        key: RSR Root CA
        property: rsr_root_ca.crt
