apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-forgejo-secret
  namespace: argocd
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: argocd-forgejo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: https://git.rsr.net
        username: '{{ printf "{{ .forgejo_username }}" }}'
        password: '{{ printf "{{ .forgejo_token }}" }}'
  dataFrom:
    - extract:
        key: forgejo-config
