longhorn:
  networkPolicies:
    enabled: false
    restrictInternalTraffic: false
  persistence:
    defaultClassReplicaCount: "2"
  defaultSettings:
    defaultReplicaCount: "2"
    createDefaultDiskLabeledNodes: true
    backupTarget: s3://longhorn@us-east-1/
    backupTargetCredentialSecret: longhorn-backup-secret
    storageMinimalAvailablePercentage: "10"
    taintToleration: arm64=true:NoExecute
    engineImagePodLivenessProbePeriod: 15
    engineImagePodLivenessProbeTimeout: 30
    engineImagePodLivenessProbeFailureThreshold: 10
    
    instanceManagerPodLivenessProbeTimeout: 20
    # Protects the instance manager pods from identical timeout loops
    engineReplicaTimeout: 20

  #Temp fix
#  preUpgradeChecker:
#    upgradeVersionCheck: false
#  image:
#    longhorn:
#      instanceManager:
#        repository: longhornio/longhorn-instance-manager
#        tag: v1.11.0-hotfix-1
##
#      manager:
#        repository: longhornio/longhorn-manager
#        tag: v1.11.0-hotfix-1

