{
 "title": "ServerTracker",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Server Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Info",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "server_last_reboot_time{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_last_login_time{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_last_updated_time{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_updates_available{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_reboot_needed{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(server_last_push_time{job=\"pushgateway\"} - server_last_reboot_time{job=\"pushgateway\"})/ 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "sgn(((time() - server_last_push_time{job=\"pushgateway\"}) / 60)-16) /2 + 0.5",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU and Mem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "server_mem_usage{job=\"pushgateway\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_cpu_usage{job=\"pushgateway\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_disk_space_used{job=\"pushgateway\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}