app-template:

  image:
    repository: ghcr.io/k8s-at-home/unpoller
    tag: 2.1.3

  service:
    main:
      enabled: true
      ports:
        http:
          enabled: false
        metrics:
          port: &port 9130

  env:
    TZ: "America/Chicago"
    UP_UNIFI_DEFAULT_ROLE: "homelab-controller"
    UP_UNIFI_DEFAULT_URL:
      valueFrom:
        secretKeyRef:
          name: unifi-poller-secret
          key: UNIFI_URL
    UP_UNIFI_DEFAULT_VERIFY_SSL: false
    UP_UNIFI_DEFAULT_USER:
      valueFrom:
        secretKeyRef:
          name: unifi-poller-secret
          key: UNIFI_USER
    UP_UNIFI_DEFAULT_PASS:
      valueFrom:
        secretKeyRef:
          name: unifi-poller-secret
          key: UNIFI_PASSWORD
    UP_UNIFI_DEFAULT_SAVE_SITES: true
    UP_UNIFI_DEFAULT_SAVE_DPI: false
    UP_INFLUXDB_DISABLE: true
    UP_PROMETHEUS_DISABLE: false
    UP_PROMETHEUS_NAMESPACE: "unifipoller"

  serviceMonitor:
    main:
      enabled: true
      endpoints:
        - port: metrics
          path: /metrics
          interval: 1m
          scrapeTimeout: 30s

# GrafanaDashboard CRs for this app, rendered via templates/grafanadashboard.yaml
grafanaDashboards:
  - name: unifi-insights
    namespace: monitoring
    folder: networking
    # renovate: depName=11315
    url: https://grafana.com/api/dashboards/11315/revisions/9/download
    datasources:
      - inputName: DS_PROMETHEUS
        datasourceName: Prometheus
  - name: unifi-network-sites
    namespace: monitoring
    folder: networking
    # renovate: depName=11311
    url: https://grafana.com/api/dashboards/11311/revisions/5/download
    datasources:
      - inputName: DS_PROMETHEUS
        datasourceName: Prometheus
  - name: unifi-uap
    namespace: monitoring
    folder: networking
    # renovate: depName=11314
    url: https://grafana.com/api/dashboards/11314/revisions/10/download
    datasources:
      - inputName: DS_PROMETHEUS
        datasourceName: Prometheus
  - name: unifi-usw
    namespace: monitoring
    folder: networking
    # renovate: depName=11312
    url: https://grafana.com/api/dashboards/11312/revisions/9/download
    datasources:
      - inputName: DS_PROMETHEUS
        datasourceName: Prometheus




