
external-secrets:
  installCRDs: true
  replicaCount: 1
  serviceMonitor:
    enabled: true
  webhook:
    serviceMonitor:
      enabled: true
  certController:
    serviceMonitor:
      enabled: true
  grafanaDashboard:
    enabled: true

grafanaDashboards:
  - name: external-secrets
    namespace: kube-system
    allowCrossNamespaceImport: true
    folder: node-metrics
    url: https://raw.githubusercontent.com/external-secrets/external-secrets/main/docs/snippets/dashboard.json
    datasources:
      - inputName: DS_PROMETHEUS
        datasourceName: Prometheus
