descheduler:
  replicas: 2
  kind: Deployment
  tolerations:
    - key: "arm64"
      operator: "Exists"
    - key: "arm"
      operator: "Exists"
  deschedulerPolicyAPIVersion: descheduler/v1alpha2
  deschedulerPolicy:
    profiles:
      - name: Default
        pluginConfig:
          - name: DefaultEvictor
            args:
              nodeFit: true
              podProtections:
                defaultDisabled:
                  - FailedBarePods
                  - PodsWithLocalStorage
                  - SystemCriticalPods
          - name: RemoveFailedPods
            args:
              reasons:
                - ContainerStatusUnknown
                - NodeAffinity
                - NodeShutdown
                - Terminated
                - UnexpectedAdmissionError
              includingInitContainers: true
              excludeOwnerKinds:
                - Job
              minPodLifetimeSeconds: 1800
          - name: RemovePodsViolatingInterPodAntiAffinity
          - name: RemovePodsViolatingNodeAffinity
            args:
              nodeAffinityType:
                - requiredDuringSchedulingIgnoredDuringExecution
          - name: RemovePodsViolatingNodeTaints
          - name: RemovePodsViolatingTopologySpreadConstraint
            args:
              constraints:
                - DoNotSchedule
                - ScheduleAnyway
          - name: RemoveDuplicates
          - name: RemovePodsHavingTooManyRestarts
            args:
              podRestartThreshold: 100
              includingInitContainers: true
          - name: LowNodeUtilization
            args:
              numberOfNodes: 1
              evictionLimits:
                node: 5
              thresholds:
                cpu: 15
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 85
                memory: 85
                pods: 80
          - name: PodLifeTime
            args:
              maxPodLifeTimeSeconds: 86400
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - frigate

        plugins:
          balance:
            enabled:
              - RemoveDuplicates
              - RemovePodsViolatingTopologySpreadConstraint
              - LowNodeUtilization
          deschedule:
            enabled:
              - RemovePodsHavingTooManyRestarts
              - RemovePodsViolatingNodeTaints
              - RemovePodsViolatingNodeAffinity
              - RemovePodsViolatingInterPodAntiAffinity
              - RemoveFailedPods
              - PodLifeTime

  service:
    enabled: true
  serviceMonitor:
    enabled: true
  leaderElection:
    enabled: true
