# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "context7-mcp.fullname" . }}
  labels:
    {{- include "context7-mcp.labels" . | nindent 4 }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: {{ include "context7-mcp.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: context7-config
        property: api-key
