# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgpadvertisement_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisement
  labels:
    advertise: bgp
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - key: fakeSelector
            operator: NotIn
            values:
              - will-match-and-announce-all-services
---
