kopiur:
  installScope: cluster
  streamingLists: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 2Gi
  features:
    credentialProjection:
      enabled: true
  webhook:
    tls:
      mode: self
  monitoring:
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
