{{- range .Values.datasources }}
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ .name }}
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  {{- if .valuesFrom }}
  valuesFrom:
{{ toYaml .valuesFrom | indent 4 }}
  {{- end }}
  datasource:
{{ toYaml .datasource | indent 4 }}
{{- end }}
