---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ printf "{{.grafana_client_id }}" }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ printf "{{.grafana_client_secret }}" }}"
        TESLAMATE_DB_PASSWORD: "{{ printf "{{.teslamate_password }}" }}"

  dataFrom:
    - extract:
        key: pocket-id-config
    - extract:
        key: postgres-config
