---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: grafana
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
  annotations:
    secret.reloader.stakater.com/reload: "grafana-secret"
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "true"
    auth.generic_oauth:
      enabled: "true"
      allow_sign_up: "true"
      auto_login: "false"
      name: pocket-id
      scopes: "openid email profile groups"
      auth_url: https://pi.rsr.net/authorize
      token_url: http://pocket-id.kube-system.svc.cluster.local:1411/api/oidc/token
      api_url: http://pocket-id.kube-system.svc.cluster.local:1411/api/oidc/userinfo
    auth.generic_oauth.group_mapping:
      role_attribute_path: "contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'editor') && 'Editor' || 'Viewer'"
    date_formats:
      use_browser_locale: "true"
    log:
      mode: console
    news:
      news_feed_enabled: "false"
    security:
      angular_support_enabled: "true"
      allow_embedding: "true"
      cookie_samesite: grafana
    server:
      root_url: https://grafana.rsr.net
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_INSTALL_PLUGINS
                  value: victoriametrics-logs-datasource
              envFrom:
                - secretRef:
                    name: grafana-secret
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
          securityContext:
            runAsNonRoot: true
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: tmp
              emptyDir: {}
            - name: grafana-data
              emptyDir: {}
  disableDefaultSecurityContext: All
  httpRoute:
    metadata:
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Monitoring
        gethomepage.dev/icon: grafana
        gethomepage.dev/name: Grafana
    spec:
      parentRefs:
        - name: internal
          namespace: kube-system
          sectionName: https
      hostnames:
        - grafana.rsr.net
