# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "litellm.fullname" . }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: {{ include "litellm.fullname" . }}
    creationPolicy: Owner
    template:
      data:
        LITELLM_MASTER_KEY: '{{ printf "{{ .litellm_master_key }}" }}'
  dataFrom:
    - extract:
        key: litellm-config