apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-step-ca-root
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  rules:
    - name: clone-step-ca-configmap
      match:
        resources:
          kinds:
            - ConfigMap
          names:
            - step-certificates-certs
          namespaces:
            - kube-system
      generate:
        apiVersion: v1
        kind: ConfigMap
        name: step-certificates-certs
        namespace: cert-manager
        synchronize: true
        clone:
          namespace: kube-system
          name: step-certificates-certs
