apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: step-ca-bundle
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  sources:
    - secret:
        name: step-ca-root-cert
        key: ca.crt

  target:
    configMap:
      key: ca.crt
    namespaceSelector:
      matchLabels:
        trust: enabled
