apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-ca-root-cert
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect

  target:
    name: step-ca-root-cert
    creationPolicy: Owner
    template:
      engineVersion: v2

  data:
    - secretKey: ca.crt
      remoteRef:
        key: RSR Root CA
        property: rsr_root_ca.crt
