gateway-helm:
  config:
    envoyGateway:
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      extensionApis:
        enableBackend: true


error-pages:
  global:
    nameOverride: error-pages
  controllers:
    error-pages:
      replicas: 2
      strategy: RollingUpdate
      containers:
        app:
          image:
            repository: ghcr.io/tarampampam/error-pages
            tag: 4.2.5
          env:
            TEMPLATE_NAME: orient
            SHOW_DETAILS: "false"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
          resources:
            requests:
              cpu: 5m
              memory: 16M
            limits:
              memory: 32M
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ "ALL" ]

  service:
    app:
      controller: error-pages
      ports:
        http:
          port: 8080

grafanaDashboards:
  - name: envoy-overview
    namespace: kube-system
    allowCrossNamespaceImport: true
    folder: networking
    # renovate: depName=24459
    url: https://grafana.com/api/dashboards/24459/revisions/3/download
    datasources:
      - inputName: DS_PROMETHEUS
        datasourceName: Prometheus
  - name: envoy-upstream
    namespace: kube-system
    allowCrossNamespaceImport: true
    folder: networking
    # renovate: depName=24457
    url: https://grafana.com/api/dashboards/24457/revisions/4/download
    datasources:
      - inputName: DS_PROMETHEUS
        datasourceName: Prometheus
  - name: envoy-downstream
    namespace: kube-system
    allowCrossNamespaceImport: true
    folder: networking
    # renovate: depName=24458
    url: https://grafana.com/api/dashboards/24458/revisions/3/download
    datasources:
      - inputName: DS_PROMETHEUS
        datasourceName: Prometheus
