apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
  namespace: default
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: '{{ printf "{{ .forgejo_runner_k8s_token }}" }}'
        uuid: '{{ printf "{{ .forgejo_runner_k8s_uuid }}" }}'
        cache_token: '{{ printf "{{ .forgejo_runner_cache_token }}" }}'
  dataFrom:
    - extract:
        key: forgejo-config
