---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-operator
  namespace: default
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}  # Add this!
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: '{{ printf "{{ .RENOVATE_TOKEN }}" }}'
        RENOVATE_GITHUB_COM_TOKEN: '{{ printf "{{ .GH_COM_TOKEN }}" }}'
        ssh_private_key: |
          {{ printf "{{ .ssh_private_key }}" }}
  dataFrom:
    - extract:
        key: renovate-config
