---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret
  namespace: default
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: garage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GARAGE_RPC_SECRET: '{{ printf "{{ .GARAGE_RPC_SECRET }}" }}'
        GARAGE_ADMIN_TOKEN: '{{ printf "{{ .GARAGE_ADMIN_TOKEN }}" }}'
        GARAGE_METRICS_TOKEN: '{{ printf "{{ .GARAGE_METRICS_TOKEN }}" }}'
  dataFrom:
    - extract:
        key: garage-config
